#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := simple_wifi
EXTRA_LDFLAGS = -L$(CURDIR)/mDash/src/esp32 -lmDash  # <-- add this line
include $(IDF_PATH)/make/project.mk

